export { default as themeStore } from "store/theme"
export { default as menuStore } from "store/menu"
export { default as wallpaperStore } from "./wallpaper"
export { default as desktopStore } from "./desktop"
export { default as websiteInfoStore } from "./websiteInfo"
export { default as websiteEditStore } from "./websiteEdit"
export { default as folderStore } from "./folder"
export { default as shortcutIconsStore } from "./shortcutIcons"
